### PR TITLE
Added missing files to compile CommonCrypto

### PR DESCRIPTION
**Pull request by sundance2000**
Hi,

your framework is a great help and works perfectly. Thank you very much!
It seems that you forgot two add some files when creating the master branch.
I added the missing files from the 2.3 branch, now everything should work.
Maybe you want to re-check, if some project files need to be adapted, too.

Kind Regards,
Christian Oberdörfer

### CODE REVIEW

**Comment by cbaker6** [comment]
After taking a closer look, it turns out you added CommonCrypto files manually. In the original, CommonCypto was added as an additional framework, the files are already available to iOS and don't need to be re-copied. In the updated version, the framework isn't needed anymore

**Comment by pfupload** [comment]
Thank you for reviewing my request but your change does not work for me. If I try to compile the framework I get lots of errors because CommonCrypto cannot be found.

I seems that #import <CommonCrypto/CommonCrypto.h> does not work in Swift frameworks, so the additional module is still needed. This problem is discussed in detail here: http://stackoverflow.com/questions/25248598/importing-commoncrypto-in-a-swift-framework
https://forums.developer.apple.com/thread/46477

**Comment by sundance2000** [comment]
Thank you for reviewing my request but your change does not work for me. If I try to compile the framework I get lots of errors because CommonCrypto cannot be found.

I seems that #import <CommonCrypto/CommonCrypto.h> does not work in Swift frameworks, so the additional module is still needed. This problem is discussed in detail here: http://stackoverflow.com/questions/25248598/importing-commoncrypto-in-a-swift-framework
https://forums.developer.apple.com/thread/46477

**Comment by sundance2000** [comment]
Thank you for reviewing my request but your change does not work for me. If I try to compile the framework I get lots of errors because CommonCrypto cannot be found.

I seems that #import <CommonCrypto/CommonCrypto.h> does not work in Swift frameworks, so the additional module is still needed. This problem is discussed in detail here: http://stackoverflow.com/questions/25248598/importing-commoncrypto-in-a-swift-framework
https://forums.developer.apple.com/thread/46477

**Comment by cbaker6** [comment]
@sundance2000 yes, sorry about that. It seems that Xcode is kind of finicky with including header files in a framework. When I was on Xcode 7 it never worked, when I tried it again recently it worked even after cleaning the project, but after I changed the project name, it started messing up again. So I've moved away from it...

I've made changes to the project and now it only uses one framework in an attempt to place the project on cocoapods, but I couldn't get it to pass lint. The only way I could figure out how to get it sort of ready for cocoapods was to copy the CommonCrypto files directly to the project (this should work if you clone the main branch).  If you would rather use the project with CommonCrypto as an additional framework and references to the local CommonCrypto files provided by Apple it's best to use the "withCryptoFramework" branch.

**Pull request merged**
